REM Auto-generated by Bat_NPM v1.0, Project ID: [e505058e], datetime[20231128175515]

REM 不顯示命令提示符  
@echo off 

REM UTF-8 支援中文  
chcp 65001 

REM 執行額外NPM安裝-開發
npm install --save-dev @babel/preset-env @babel/preset-typescript @jest/globals @types/jest @types/node jest ts-jest ts-node typescript

REM 執行額外NPM安裝-核心
npm install reflect-metadata sqlite3 typeorm

REM 暫停  
pause 